# Generated by Django 5.0.2 on 2024-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='Here will be a description soon!'),
        ),
        migrations.AlterField(
            model_name='title',
            name='published_date',
            field=models.DateField(),
        ),
    ]
