# Generated by Django 5.0.2 on 2024-03-01 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
