# Generated by Django 5.0.2 on 2024-03-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_alter_comment_published_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
    ]
